version: "3"
services:
  db:
    image: postgres:15
    container_name: cards_db
    env_file: secret.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    expose:
      - 5432

  backend:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    container_name: cards_backend
    env_file: secret.env
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - db
