"""users_and_token_table

Revision ID: 067f5374743c
Revises: 
Create Date: 2023-03-16 23:40:45.428803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "067f5374743c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=63), nullable=True),
        sa.Column("email", sa.String(length=63), nullable=False),
        sa.Column("password", sa.String(length=63), nullable=True),
        sa.Column("first_name", sa.String(length=63), nullable=True),
        sa.Column("last_name", sa.String(length=63), nullable=True),
        sa.Column("verified", sa.Boolean(), server_default="f", nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "token",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(length=63), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.UniqueConstraint("value"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("token")
    op.drop_table("user")
    # ### end Alembic commands ###
