"""add_subscriber_field_to_user

Revision ID: 367e3d7d3d3f
Revises: 58be826d284b
Create Date: 2023-03-28 02:33:49.412230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "367e3d7d3d3f"
down_revision = "58be826d284b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("subscriber", sa.Boolean(), server_default="f", nullable=False),
    )
    op.add_column("user", sa.Column("subscribe_end", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "subscribe_end")
    op.drop_column("user", "subscriber")
    # ### end Alembic commands ###
