"""add_unique_constraint_user_email

Revision ID: 488815df71c8
Revises: c22ed0931890
Create Date: 2023-03-17 04:07:34.800253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488815df71c8'
down_revision = 'c22ed0931890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
