"""add_need_chatgpt_field

Revision ID: 7701114d9447
Revises: 367e3d7d3d3f
Create Date: 2023-03-30 19:27:52.155165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7701114d9447'
down_revision = '367e3d7d3d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('need_chatgpt', sa.Boolean(), server_default='f', nullable=True))
    op.add_column('category', sa.Column('need_chatgpt', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'need_chatgpt')
    op.drop_column('card', 'need_chatgpt')
    # ### end Alembic commands ###
