"""add_unique_constraint_for_cards

Revision ID: b7009fb55b5b
Revises: 5afa67010df1
Create Date: 2023-03-30 20:50:19.780233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7009fb55b5b'
down_revision = '5afa67010df1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('title_user_unique_card', 'card', ['title', 'user_id'])
    op.create_unique_constraint('title_user_unique_category', 'category', ['title', 'user_id'])
    op.create_unique_constraint('category_user_unique_related_system_categories_with_user', 'related_system_categories_with_user', ['category_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_user_unique_related_system_categories_with_user', 'related_system_categories_with_user', type_='unique')
    op.drop_constraint('title_user_unique_category', 'category', type_='unique')
    op.drop_constraint('title_user_unique_card', 'card', type_='unique')
    # ### end Alembic commands ###
