"""add_created_and_updated_columns_to_user

Revision ID: c22ed0931890
Revises: 067f5374743c
Create Date: 2023-03-17 02:03:56.380719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c22ed0931890"
down_revision = "067f5374743c"
branch_labels = None
depends_on = None


# create_trigger_query = f"""
# CREATE OR REPLACE FUNCTION update_datetime_updated_column()
# RETURNS TRIGGER AS $update_datetime_updated_column$
# BEGIN
#     NEW.updated=now();
#     RETURN NEW;
# END; $update_datetime_updated_column$
# LANGUAGE plpgsql;

# CREATE TRIGGER update_datetime_updated_column_trigger
# BEFORE UPDATE ON "user"
# FOR EACH ROW
# EXECUTE FUNCTION update_datetime_updated_column();
# """


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.add_column("user", sa.Column("updated", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "updated")
    op.drop_column("user", "created")
    # ### end Alembic commands ###
