name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort
      - name: Analysing the code with pylint
        run: |
          isort app --src=app/ --skip=app/alembic --profile=black --check && black app --exclude=app/alembic --check
