name: Test

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run dev container
        run: docker-compose -f docker-compose.dev.yml up -d
      - name: Test with pytest
        run: docker exec -t cards_backend pytest -s
